"""Constants for GeoMotion."""

DOMAIN = "geo_motion"
SUBENTRY_TYPE_TRACKED_ENTITY = "tracked_entity"

CONF_SOURCE_ENTITY = "source_entity"
CONF_HISTORY_WINDOW = "history_window"
CONF_COMPARISON_AGE = "comparison_age"
CONF_MIN_REFERENCE_AGE = "min_reference_age"
CONF_MIN_DISTANCE_M = "min_distance_m"
CONF_DEFAULT_ACCURACY = "default_accuracy"
CONF_STATIONARY_TIMEOUT = "stationary_timeout"

DEFAULT_HISTORY_WINDOW = 600
DEFAULT_COMPARISON_AGE = 300
DEFAULT_MIN_REFERENCE_AGE = 60
DEFAULT_MIN_DISTANCE_M = 20
DEFAULT_DEFAULT_ACCURACY = 25
DEFAULT_STATIONARY_TIMEOUT = 120

ENTITY_REFRESH_INTERVAL = 60
MIN_SAMPLE_SPACING_SECONDS = 5
MAX_HISTORY_SAMPLES = 240
